# Use the official Go image as the base image
FROM golang:1.25 AS builder

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum to install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

RUN wget https://github.com/vultisig/go-wrappers/archive/refs/heads/master.tar.gz
RUN tar -xzf master.tar.gz && \
    cd go-wrappers-master && \
    mkdir -p /usr/local/lib/dkls && \
    cp --recursive includes /usr/local/lib/dkls

ENV LD_LIBRARY_PATH=/usr/local/lib/dkls/includes/linux/:$LD_LIBRARY_PATH
ENV CGO_LDFLAGS="-L/usr/local/lib/dkls/includes/linux -lgodkls -lgoschnorr"
ENV CGO_ENABLED=1

# Build the application
RUN go build -o agent-worker ./cmd/worker

# Use a minimal base image for the final stage
FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the built binary from the builder stage
COPY --from=builder /app/agent-worker .
COPY --from=builder /usr/local/lib/dkls /usr/local/lib/dkls
COPY agent.yaml config.yaml

ENV LD_LIBRARY_PATH=/usr/local/lib/dkls/includes/linux/:$LD_LIBRARY_PATH

# Run the application
CMD ["./agent-worker"]